config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:show, :index]
  resources :groups, only: [:show, :index]
  resources :tags, only: [:index]
  root to: 'home#index'
  namespace :admin do
    root to: "articles#index"
    resources :articles, only: [:edit, :destroy, :index, :new, :update, :create]
    resources :groups, only: [:edit, :destroy, :index, :new, :update, :create]
    resources :exception_logs, only: [:show, :destroy, :index] do
      delete :destroy_multiple, on: :collection
    end
  end
  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end

  patch '/photos', to: "photos#create"
  get 'tags/:tag_id', to: 'articles#index', as: :tag
end

app/models/admin/exception_log.rb
class Admin::ExceptionLog < ActiveRecord::Base
end

app/controllers/admin/exception_logs_controller.rb
class Admin::ExceptionLogsController < Admin::BaseController
  before_action :set_admin_exception_log, only: [:show, :destroy]

  def index
    @admin_exception_logs = Admin::ExceptionLog.order("id DESC").page(params[:page]).per(20)
  end

  def show
  end

  def destroy
    @admin_exception_log.destroy
    respond_to do |format|
      format.html { redirect_to admin_exception_logs_url, notice: 'Exception log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    Admin::ExceptionLog.delete(params[:admin_exception_log_ids])
    flash[:danger] = '删除成功'
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_exception_log
      @admin_exception_log = Admin::ExceptionLog.find(params[:id])
    end
end

app/views/admin/exception_logs/index.html.slim
h2 所有异常

= form_tag destroy_multiple_admin_exception_logs_path, method: :delete
  table.table
    p.text-right
      button#destroy_multiple type="submit" class="btn btn-danger btn-sm" disabled="disabled"
        |删除
    tr
      th
        input type="checkbox" id="checkAll" value="checkAll" class="check"
        label for="checkAll"
      th id
      th 时间
      th title
      th body
      th 操作
    - @admin_exception_logs.each do |admin_exception_log|
      tr
        td = check_box_tag 'admin_exception_log_ids[]', admin_exception_log.id, nil, :id => "admin_exception_log_#{admin_exception_log.id}", class: "check"
        td = admin_exception_log.id
        td = datetime admin_exception_log.created_at
        td = admin_exception_log.title
        td = link_to(truncate(admin_exception_log.body), admin_exception_log)
        td = link_to 'Destroy', admin_exception_log, method: :delete, data: { confirm: 'Are you sure?' }
= paginate @admin_exception_logs

coffee:
  jQuery ->
    $('#checkAll').checkAll('.check')
    $(".check").checkDisable("#destroy_multiple")

app/views/admin/exception_logs/show.html.slim
p
  strong Title:
  = @admin_exception_log.title
p
  strong Body:
  = simple_format @admin_exception_log.body

= link_to 'Back', admin_exception_logs_path