config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:show, :index]
  resources :groups, only: [:show, :index]
  resources :tags, only: [:index]
  root to: 'home#index'
  namespace :admin do
    root to: "articles#index"
    resources :articles, only: [:edit, :destroy, :index, :new, :update, :create]
    resources :groups, only: [:edit, :destroy, :index, :new, :update, :create]
    resources :exception_logs, only: [:show, :destroy, :index] do
      delete :destroy_multiple, on: :collection
    end
  end
  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end

  patch '/photos', to: "photos#create"
  get 'tags/:tag_id', to: 'articles#index', as: :tag
end

app/models/article.rb
require "babosa"
class Article < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_title_or_body,
                  :against => {
                    :title => 'A',
                    :body => 'B'
                  },
                  :associated_against => {
                    :tags => [:name],
                  },
                  :using => {
                    :tsearch => {:dictionary => "testzhcfg", :prefix => true, :negation => true}
                  }
  acts_as_taggable
  ActsAsTaggableOn.remove_unused_tags = true
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders, :history]
  belongs_to :group, counter_cache: true
  scope :published, -> { where(published: true) }
  scope :except_body_with_default, -> { published.select(:title, :created_at, :published, :group_id, :slug, :id).includes(:group) }
  validates :title, :body, presence: true
  validates :title, uniqueness: true

  def normalize_friendly_id(input)
    date = if self.created_at.present?
             created_at.strftime('%Y-%m-%d')
           else
             Time.zone.now.strftime('%Y-%m-%d')
           end
    "#{date}-#{PinYin.of_string(input).to_s.to_slug.normalize.to_s}"
  end

  def set_friendly_id
    self.slug = "#{created_at.strftime('%Y-%m-%d')}-#{self.slug}"
  end

  def should_generate_new_friendly_id?
    title_changed? || super
  end

  alias_method :old_tag_list, :tag_list
  def tag_list
    super.join(", ")
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:edit, :update, :destroy]

  def index
    @articles = Article.includes(:group).order("id DESC").page(params[:page])
    render 'articles/index'
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_root_path, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :published, :group_id, :tag_list)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  def index
    if params[:search].present?
      @articles = Article.except_body_with_default.search_by_title_or_body(params[:search]).order("id DESC").page(params[:page])
    elsif params[:tag_id] && @tag = ActsAsTaggableOn::Tag.find_by(id: params[:tag_id])
      @articles = Article.except_body_with_default.tagged_with(@tag.name).order("id DESC").page(params[:page])
    else
      @articles = Article.except_body_with_default.order("id DESC").page(params[:page])
    end
    set_meta_tags title: '文章列表', description: "提供rails文章和视频教程，知识和信息交流", keywords: ActsAsTaggableOn::Tag.most_used.map(&:name).join(", ")
  end

  def show
    set_meta_tags title: @article.title, description: @article.title, keywords: @article.tag_list
    @group_name = @article.group.try(:name) || ""
    @recommend_articles = Article.except_body_with_default.search_by_title_or_body(@group_name).order("visit_count DESC").limit(11)
    @tags = @article.tag_counts_on(:tags)
  end

  private
    def set_article
      @article = Article.find(params[:id])
      if request.path != article_path(@article)
        return redirect_to @article, :status => :moved_permanently
      end
    end

end

app/views/articles/edit.html.slim
.page-header
  h2 Editing article

== render 'articles/form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path
'|
= link_to 'Destroy', admin_article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }

app/views/articles/index.html.slim
.page-header
  - if @tag.present?
    h2 标签<strong>#{@tag.name}</strong>下的所有文章
  - else
    h2 所有文章(#{@articles.total_count})

- if session[:admin]
  .text-right
    = link_to "添加新文章", new_admin_article_path
- @articles.each do |article|
  - if params[:search].present?
    h3 = link_to article.title.html_safe, article, class: "search-hight-light"
  - else
    h3 = link_to article.title, article
  p.text-right
    = raw article.tags.map { |t| link_to t.name, tag_path(t.id) }.join(', ')
  p.text-right
    - if article.group
      span.label.label-default = link_to article.group.try(:name), group_path(article.group)
    span.text-muted
      | *创建于
      = datetime article.created_at
    - if session[:admin]
      span.label.label-default = article.published
      = link_to 'Destroy', [:admin, article], method: :delete, data: { confirm: 'Are you sure?' }
= paginate @articles

app/views/articles/new.html.slim
.page-header
  h2 New article

== render 'articles/form'

app/views/articles/show.html.slim
.page-header
  h2 = @article.title
.row
  .col-md-12.block-margin
    .text-right
      = datetime @article.created_at
      - if session[:admin]
        = link_to "编辑", edit_admin_article_path(@article)
.row
  .col-md-8
    = markdown @article.body
    hr
    = render 'disqus'
  .col-md-4
    .panel.panel-default
      .panel-heading
        div 扫一扫分享到微信
      .panel-body
        #qrcode
    .panel.panel-default
      .panel-heading
        div 相关推荐
      .panel-body
        - @recommend_articles.each do |recommend_article|
          - unless recommend_article.id == @article.id
            p = link_to recommend_article.title, recommend_article
    .panel.panel-default
      .panel-heading
        div 标签
      .panel-body
        - tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
          div
            = link_to tag.name, tag_path(tag.id), class: css_class

javascript:
  $(document).ready(function() {
    new QRCode(document.getElementById("qrcode"), {
      text: "#{article_url(@article)}",
      width: 128,
      height: 128});
    $('a.fluidbox-link').fluidbox();
  });