config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:show, :index]
  resources :groups, only: [:show, :index]
  resources :tags, only: [:index]
  root to: 'home#index'
  namespace :admin do
    root to: "articles#index"
    resources :articles, only: [:edit, :destroy, :index, :new, :update, :create]
    resources :groups, only: [:edit, :destroy, :index, :new, :update, :create]
    resources :exception_logs, only: [:show, :destroy, :index] do
      delete :destroy_multiple, on: :collection
    end
  end
  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end

  patch '/photos', to: "photos#create"
  get 'tags/:tag_id', to: 'articles#index', as: :tag
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :articles, dependent: :nullify
  validates :name, presence: true
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController
  before_action :set_group, only: [:edit, :update, :destroy]

  def index
    @groups = Group.all
    render 'groups/index'
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show]

  def index
    @groups = Group.all
    set_meta_tags title: "分类列表", description: "提供rails文章和视频教程，知识和信息交流", keywords: @groups.map(&:name).join(", ")
  end

  def show
    set_meta_tags title: @group.name, description: @group.name, keywords: @group.articles.map(&:tag_list)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end
end

app/views/admin/groups/_form.html.slim
= form_for [:admin, @group], html: {class: "form-horizontal"} do |f|
  - if @group.errors.any?
    #error_explanation
      h2 = "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      ul
        - @group.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    .col-sm-10.col-sm-offset-2
      = f.submit "save", class: "btn btn-primary"

app/views/admin/groups/edit.html.slim
h1 Editing group

== render 'form'

= link_to 'Show', @group
'|
= link_to 'Back', groups_path

app/views/admin/groups/new.html.slim
.page-header
  h2 New group

== render 'form'

= link_to 'Back', admin_groups_path